### PR TITLE
Issue#39 auto add missing headers

### LINKED ISSUE #39: Board not in GBB format error
### Example

``` json

{
		"content" : "procedure SalirDeLineaVerde(direccion) {\nwhile (hayBolitas(Verde)){\nMover(direccion)\n}\n}",
		"test" : "check_head_position: true\n\nsubject: SalirDeLineaVerde\n\nexamples:\n - arguments:\n   - Este\n   initial_board: |\n     GBB/1.0\n     size 5 2\n     cell 0 0 Verde 1\n     cell 1 0 Verde 1\n     cell 2 0 Verde 1\n     head 0 0\n   final_board: |\n     GBB/1.0\n     size 5 2\n     cell 0 0 Verde 1\n     cell 1 0 Verde 1\n     cell 2 0 Verde 1\n     head 3 0\n     \n - arguments:\n   - Sur\n   initial_board: |\n     GBB/1.0\n     size 3 4\n     cell 1 3 Verde 1\n     head 1 3\n   final_board: |\n     size 3 4\n     cell 1 3 Verde 1\n     head 1 2",
		"expectations" : [ ],
		"extra" : "",
		"language" : "gobstones"
}
```

### Result

The variable output in this line: https://github.com/mumuki/mumuki-gobstones-runner/blob/master/lib/expectations_hook.rb#L9 has this value: `{:status=>"all_is_broken_error", :message=>"Something has gone very wrong", :detail=>{}, :moreDetail=>"GBB/1.0: Board not in GBB/1.0 format."}`

### PR DESCRIPTION
**Pull request by julian-berbel**
Fixes #39.

### CODE REVIEW

File: spec/integration_spec.rb [hunk 1]
```diff
@@ -118,6 +139,7 @@
      size 2 2
      head 0 0
    final_board: |
+     GBB/1.0
```
Comment (flbulgarelli) [inline spec/integration_spec.rb]: @julian-berbel I added a more explicit test here :)
